### ISSUE TITLE
[Issue] `ibzmq.dll` not found

### ISSUE THREAD

**Issue by hoomanBT** [Voltstro-Studios/UnityWebBrowser#15]
hi
after i re install my windows os and after i import my project to unity and open scene that contain browser its giving me this error:
DllNotFoundException: libzmq
ZeroMQ.lib.zmq..cctor () (at <7ef98cc71ceb41998304e67bb43d6dc5>:0)
i check for libzmq.dll on ther project and its there in the Plugins\CefBrowser folder

**Comment by Voltstro** [comment]
Hello.

What version of this project are you using?
Is it from the GitLab package? 

I am going to assume that you did use the GitLab package version, since the error you gave mentions libzmq, and the current in-development version no longer uses it.

If you did use the GitLab package version then you shouldn't have any issues with it, the best help I can offer right now without the answers to the questions I asked above is to make sure you followed the install instructions for that version and to re-import the package.
Also make sure your project isn't at some crazy path that has spaces or characters like that.

**Comment by Voltstro** [comment]
Well that is quite strange and even I wouldn't know what is going on. I will take a look further into this when I get home.

One suggestion I have right now that you could try is to copy the `libzmq.dll` into your own project's `Plugins/` directory and see if that does anything.

**Comment by Voltstro** [comment]
Ok so I had a look. Using Unity 2020.3.15f2 with the latest stable package version on Windows seems fine to me. I have no clue what could possibly be going wrong for you.

![image](https://user-images.githubusercontent.com/45032877/128167166-78e2790c-5148-4f47-970d-cd0e0497b5cd.png)

**Comment by Voltstro** [comment]
UWB 2.0 doesn't use libzmq anymore, so this issue no longer applies.
