### ISSUE TITLE
[Issue] UnityWebBrowser (TMP) Sample Not Working

### ISSUE THREAD

**Issue by RMichaelPickering** [Voltstro-Studios/UnityWebBrowser#248]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2023.2.3f1

### Describe what the issue you are experiencing is.

Tried to customize the sample prefab "UnityWebBrowser (TMP" from "Basic" samples but the script "WebBrowserUIControlsTMP is missing from the BrowserController object in the prefab. The sample does run in 'Play' mode and displays the Voltstro Studio website but UI controls are non-functional. There's no error message in the console but there is a warning:
The referenced script on this Behaviour (Game Object 'BrowserController') is missing!

As a further note, I'd like to switch to Unity's "New Input System" but it seems sensible to ensure the existing sample, with legacy Input Manager, is working first.

### Provide reproducible steps for this issue.

1. Created new Unity3D project using the HDRP template.
2. Followed instructions to install Voltstro UPM and the UnityWebBrowser into the project.
3. Somehow the script seems to not be set up properly on the required GameObject.

**Comment by Voltstro** [comment]
Issue occurs due to Text Mesh Pro. In prior versions of Unity, TMP was checked by checking for `com.unity.textmeshpro` package. However, in Unity 2023.2, they [merged the TMP package](https://forum.unity.com/threads/2023-2-latest-development-on-textmesh-pro.1434757/) into the `com.unity.ugui` package, and deprecated the old package.

Fixed by extending UWB's asmdef version defines to both check for old `com.unity.textmeshpro` package, and `com.unity.ugui` package. Fix will be in next release.

---

> As a further note, I'd like to switch to Unity's "New Input System"

UWB already has full support for the new input system. You need to install the input system package and enable it in player options. Then you can switch the input handler asset to the new input handler.

**Comment by Voltstro** [comment]
This issue has been fixed in the latest release.
